# Simple workflow for bumping version when pushing to main
name: Bump patch version

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "version"
  cancel-in-progress: true

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          initial_version: "0.0.0"

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: "[tagged] ${{ steps.bump-semver.outputs.new_version }}"

      - name: Download dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      # just so that we can compile, remove .env from the standalone folder later
      - name: Make .env file
        run: cp .env.example .env

      - name: Modify Version in code
        run: |
          sed -i "s/Version = \".*\"/Version = \"${{ steps.bump-semver.outputs.new_version }}\"/g" src/constants/version.ts

      - name: Compile
        run: npm run build

      - name: Remove temporary .env file from standalone folder
        run: rm .next/standalone/.env

      - name: Package files into standalone folder
        run: |
          cp -r public .next/standalone
          cp -r .next/static .next/standalone/.next/static
          cp -r assets .next/standalone
          cp -r scripts .next/standalone
          mkdir .next/standalone/src
          cp -r src/utils .next/standalone/src/utils
          cp -r src/services .next/standalone/src/services
          cp tsconfig.json .next/standalone
          cp docker-compose.yml .next/standalone
          cp .env.example .next/standalone
          cp .env.indexer.example .next/standalone
          cp nginx.conf.example .next/standalone
          cp nginx.cert.conf.example .next/standalone

      # convenient in order to run a single upload command
      - name: Create outputs folder
        run: mkdir outputs

      - name: Archive outputs
        run: |
          cd .next/standalone
          tar -czf '../../outputs/dashboard_${{ steps.bump-semver.outputs.new_version }}.tar.gz' .

      - name: Create version file
        run: echo '${{ steps.bump-semver.outputs.new_version }}' > outputs/version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # sync but don't delete files, keeps old versions but updates files that have changed
      - name: Upload outputs to S3
        run: aws s3 sync ./outputs s3://cw-build-artifacts/community

      # invalidate cloudfront cache
      - name: Invalidate Build Outputs CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id EKM5NR0TASZ5T --paths '/*'
